[project]
name = "magnets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "magpylib>=5.1.1",
    "magpylib-force>=0.3.1",
    "plotly>=6.0.1",
]
